# Generated by Django 3.1.4 on 2021-09-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='csrfmiddlewaretoken',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
    ]
