# Generated by Django 3.1.4 on 2021-09-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nde', '0003_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('correlation_graph', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('graph', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MissingValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_vals', models.IntegerField()),
                ('mean', models.DecimalField(decimal_places=2, max_digits=20)),
                ('median', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mode', models.DecimalField(decimal_places=2, max_digits=20)),
                ('memory_size', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='MissingValuesPlotting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('missing_vals_plotting', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SampleOfFirstNLastRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_rows', models.IntegerField()),
                ('last_rows', models.IntegerField()),
            ],
        ),
    ]
