# Generated by Django 3.1.4 on 2021-09-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nde', '0004_correlation_graph_missingvalues_missingvaluesplotting_sampleoffirstnlastrows'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nde.correlation')),
                ('graphs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nde.graph')),
                ('missing_vals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nde.missingvalues')),
                ('missing_vals_plotting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nde.missingvaluesplotting')),
                ('sample_of_first_n_last_rows', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nde.sampleoffirstnlastrows')),
            ],
        ),
    ]
