# Generated by Django 3.1.4 on 2021-09-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nde', '0005_eda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingvalues',
            name='mean',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='missingvalues',
            name='median',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='missingvalues',
            name='memory_size',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='missingvalues',
            name='missing_vals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='missingvalues',
            name='mode',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
