# Generated by Django 3.1.4 on 2021-10-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nde', '0007_edajson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
